name: party-n-play
services:
  db:
    build:
      context: ./docker/postgis
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  redis:
    image: "bitnami/redis:latest"
    restart: unless-stopped
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379

  nats:
    image: nats
    ports:
      - 4222:4222

volumes:
  postgres-data:
  redis-data:
