name: CI

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Cache Turbo artifacts
        uses: rharkor/caching-for-turbo@v1.8

      - name: Setup required packages
        run: |
          pnpm run setup

      - name: Run Turbo tasks concurrently
        run: turbo run lint prettier type-check --concurrency=4
