name: CI

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup pnpm with Node.js
        uses: pnpm/action-setup@v4
        with:
          standalone: true

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Turbo artifacts
        uses: rharkor/caching-for-turbo@v1.8

      - name: Setup required packages
        run: |
          pnpm install -g turbo
          pnpm run setup

      - name: Run Turbo tasks concurrently
        run: turbo run lint prettier type-check test --concurrency=4
